In [7]:
import numpy as np
import pandas as pd

In [8]:
# Create a 1D NumPy array with values from 10 to 50
arr = np.array(range(10, 51))
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [9]:
#• Create a 3×3 matrix with random integers between 1 and 100
arr = np.random.randint(1,100,size=(3,3) )
print(arr)

[[87 64 22]
 [97 71 54]
 [ 6 67 99]]


In [10]:
# Find the mean, median, and standard deviation of the array in (1)

import numpy as np

# Generate a random array with 10 values
arr = np.random.randint(1, 100, size=10)  # Random integers between 1 and 99
print("Array:", arr)

# Mean
mean_val = np.mean(arr)
print("Mean:", mean_val)

# Median
median_val = np.median(arr)
print("Median:", median_val)

# Standard Deviation
std_val = np.std(arr)
print("Standard Deviation:", std_val)

Array: [46  4 39 65 33 77 91 46 38 77]
Mean: 51.6
Median: 46.0
Standard Deviation: 24.577225229874916


In [11]:
import numpy as np

#Replace all odd numbers in the array with -1

# Generate a random array
arr = np.random.randint(1, 100, size=10)
print("Original Array:", arr)

# Replace odd numbers with -1
arr[arr % 2 == 1] = -1
print("Modified Array (odds replaced with -1):", arr)

arr = np.random.randint(0,100)

Original Array: [91 41 97 62 73 43 26 75 29 68]
Modified Array (odds replaced with -1): [-1 -1 -1 62 -1 -1 26 -1 -1 68]


In [12]:
import numpy as np

# Generate a 3×3 matrix with random integers from 0 to 99
arr = np.random.randint(0, 100, size=(3, 3))
print("Original 3x3 Matrix:\n", arr)

# Reshape into 1×9 array
reshaped_array = arr.reshape(1, 9)
print("\nReshaped 1x9 Array:\n", reshaped_array)


Original 3x3 Matrix:
 [[47 15 77]
 [44 40 35]
 [43 12  2]]

Reshaped 1x9 Array:
 [[47 15 77 44 40 35 43 12  2]]


In [13]:
# Find all elements greater than 25 in your array
import numpy as np

# Your existing array (replace with yours)
arr = np.array([12, 38, 5, 42, 27, 19, 60])

# Boolean mask of elements > 25
mask = arr > 25

# Elements greater than 25
greater_than_25 = arr[mask]

print("Mask:", mask)                    # [False  True False  True  True False  True]
print("Elements > 25:", greater_than_25) # [38 42 27 60]


Mask: [False  True False  True  True False  True]
Elements > 25: [38 42 27 60]


In [14]:
#• Count how many elements are divisible by 5
import numpy as np

arr = np.array([12,55,65,70,14,46,67])

mask = (arr % 5) == 0

count_5 = np.sum(mask)

print(count_5)












# # Your array (replace with your own variable if it already exists)
# arr = np.array([12, 38, 5, 42, 27, 19, 60, 75])

# # Boolean mask for “divisible by 5”
# mask = (arr % 5 == 0)

# # Count how many
# count_div_by_5 = np.sum(mask)

# print("Mask:", mask)                 # [False False  True False False False  True  True]
# print("Total divisible by 5:", c



3


In [15]:
# Create a Series scores with values: [87, 45, 92, 67, 55], and index as ['A', 'B', 'C',
# 'D', 'E']

import pandas as pd

scores = pd.DataFrame([87,45,92,65,85], index = ['a','b','c','d','e'])
print(scores )

    0
a  87
b  45
c  92
d  65
e  85


In [16]:
# #Create a DataFrame students with columns:
# o 'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva']
# o 'Math': [87, 45, 92, 67, 55]
# o 'Science': [78, 66, 80, 72, 60]


import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math':    [87, 45, 92, 67, 55],
    'Science': [78, 66, 80, 72, 60]
    }
)

print(df)


# import pandas as pd

# students = pd.DataFrame({
#     'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
#     'Math':    [87, 45, 92, 67, 55],
#     'Science': [78, 66, 80, 72, 60]
# })

# print(students)


      Name  Math  Science
0    Alice    87       78
1      Bob    45       66
2  Charlie    92       80
3    David    67       72
4      Eva    55       60


In [1]:
# #• Add a new column "Average" = average of Math and Science scores
# import pandas as pd
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math':    [87, 45, 92, 67, 55],
    'Science': [78, 66, 80, 72, 60]
    }
)

print(df)

df['Average'] = (df['Math'] + df['Science']) / 2

print(df)



# # Existing DataFrame
# students = pd.DataFrame({
#     'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
#     'Math':    [87, 45, 92, 67, 55],
#     'Science': [78, 66, 80, 72, 60]
# })

# # Add the "Average" column
# students['Average'] = (students['Math'] + students['Science']) / 2

# print(students)


      Name  Math  Science
0    Alice    87       78
1      Bob    45       66
2  Charlie    92       80
3    David    67       72
4      Eva    55       60
      Name  Math  Science  Average
0    Alice    87       78     82.5
1      Bob    45       66     55.5
2  Charlie    92       80     86.0
3    David    67       72     69.5
4      Eva    55       60     57.5


In [2]:
#• Sort the DataFrame by "Average" in descending order
# Sort by 'Average' in descending order
df = df.sort_values(by='Average', ascending=False)

print(df)


      Name  Math  Science  Average
2  Charlie    92       80     86.0
0    Alice    87       78     82.5
3    David    67       72     69.5
4      Eva    55       60     57.5
1      Bob    45       66     55.5


In [6]:
# • Filter students who scored more than 70 in both subjects

high_scorers = df[(df['Math']>70) & df['Science']>70]

print(df.Name)








# high_scorers = students[(students['Math'] > 70) & (students['Science'] > 70)]

# print(high_scorers)


2    Charlie
0      Alice
3      David
4        Eva
1        Bob
Name: Name, dtype: object


In [1]:
# Add a new row with missing values (e.g., name: 'Frank', Math: NaN, Science:
# NaN)

import numpy as np
import pandas as pd

# Existing DataFrame
students = pd.DataFrame({
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Math':    [87, 45, 92, 67, 55],
    'Science': [78, 66, 80, 72, 60]
})

# Add Average column
students['Average'] = (students['Math'] + students['Science']) / 2

# New row with missing values
new_row = pd.DataFrame([{
    'Name': 'Frank',
    'Math': np.nan,
    'Science': np.nan,
    'Average': np.nan
}])

# Add the row to the DataFrame
students = pd.concat([students, new_row], ignore_index=True)

print(students)


      Name  Math  Science  Average
0    Alice  87.0     78.0     82.5
1      Bob  45.0     66.0     55.5
2  Charlie  92.0     80.0     86.0
3    David  67.0     72.0     69.5
4      Eva  55.0     60.0     57.5
5    Frank   NaN      NaN      NaN


In [7]:
#• Fill missing values with column means
import pandas as pd
import numpy as np

# Original DataFrame with missing row (e.g., Frank)
students = pd.DataFrame({
    'Name':    ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Math':    [87, 45, 92, 67, 55, np.nan],
    'Science': [78, 66, 80, 72, 60, np.nan],
    'Average': [82.5, 55.5, 86.0, 69.5, 57.5, np.nan]
})

# Fill missing values with column means
students[['Math', 'Science', 'Average']] = students[['Math', 'Science', 'Average']].fillna(
    students[['Math', 'Science', 'Average']].mean()
)

print(students)


      Name  Math  Science  Average
0    Alice  87.0     78.0     82.5
1      Bob  45.0     66.0     55.5
2  Charlie  92.0     80.0     86.0
3    David  67.0     72.0     69.5
4      Eva  55.0     60.0     57.5
5    Frank  69.2     71.2     70.2


In [ ]:
#• Drop rows with any remaining NaN (if any)
# Drop rows with any remaining NaN values
students.dropna(inplace=True)

print(students)


In [ ]:
# @title Cleaning data