In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


Getting an element by index

In [ ]:
a[1, 7]

np.int64(18)

Getting element by rows

In [3]:
a[0, :]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

a[:, 2]

In [4]:
a[0, 1:-1:2]

array([2, 4, 6, 8])

In [5]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7  8  9 10]
 [11 12  2 14 15 20 17 18 19 20]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Replaing

In [7]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [9]:
new_arr = arr.reshape(2,3,2)
print(new_arr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [10]:
print(new_arr[1, 2, -1])

12


In [11]:
# Convert a 3D array to an 1D array

In [12]:
flattened_arr = new_arr.flatten()
print(flattened_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [13]:
# Convert a 2D array to an 1D array

In [14]:
new_arr = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
for element in new_arr.flatten():
  print(element)

1
2
3
4
5
6
