In [2]:
import numpy as np

In [12]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


Getting an element by index

In [14]:
a[1, 7]

np.int64(18)

Getting element by rows

In [5]:
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

Element by column

In [11]:
a[:, 2]

array([1, 2])

In [6]:
a[0, 1:-1:2]

array([2, 4, 6])

In [7]:
a[1,5] = 20

a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [8]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Replaing

In [10]:
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
