

`Load Numpy
```



In [1]:
import numpy as np

Basic

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


2d Array

In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
a.ndim

1

In [5]:
b.shape

(2, 3)

In [6]:
a.dtype

dtype('int64')

In [8]:
a = np.array([1,2,3], dtype='int16')
print(a)

[1 2 3]


In [10]:
a.dtype

dtype('int16')

In [11]:
a.itemsize

2

In [12]:
a.nbytes

6