

`Load Numpy
```



In [2]:
import numpy as np

Basic

In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


2d Array

In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
c = np.array([1,2,3,4,5,6])
print (c)

[[9. 8. 7.]
 [6. 5. 4.]]
[1 2 3 4 5 6]


In [6]:
a.ndim

1

In [5]:
b.shape

NameError: name 'b' is not defined

In [ ]:
a.dtype

In [ ]:
a = np.array([1,2,3], dtype='int16')
print(a)

In [ ]:
a.dtype

In [ ]:
a.itemsize

In [ ]:
a.nbytes