# Array Initialization

In [42]:
import numpy as np

In [43]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [44]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [45]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [46]:
np.random.rand(4,2)

array([[0.06455363, 0.88959033],
       [0.50449314, 0.882483  ],
       [0.67075928, 0.17707214],
       [0.14673089, 0.43980299]])

In [47]:
np.random.randint(-4,8, size=(3,3))

array([[-3,  5,  7],
       [ 6,  3, -1],
       [-4, -1,  2]], dtype=int32)

In [48]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [49]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [50]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)

[100   2   3]


In [52]:
a = np.array([[1,2,3,4],[2,3,5,6]])
b = np.array([[1,0,1,0],[6,7,8,9]])
c = np.concatenate((a,b), axis=1)
print(c)

[[1 2 3 4 1 0 1 0]
 [2 3 5 6 6 7 8 9]]


In [53]:
a = np.array([[1,2,3,4],[2,3,5,6]])
b = np.array([[1,0,1,0],[6,7,8,9]])
print(a.ndim)
c = np.stack((a,b)) #stack
print(c.ndim)
print(c)

2
3
[[[1 2 3 4]
  [2 3 5 6]]

 [[1 0 1 0]
  [6 7 8 9]]]


In [54]:
a = np.array([1,2,3,4,5,6,7,8])
array_split = np.split(a, 2)
print(array_split)
print(array_split[:1])

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[array([1, 2, 3, 4])]


In [55]:
arr = np.array([1,2,3,4,5,6])
x = np.where(arr == 4)
print(x)

y = np.where(arr%2==0)
print(y)

z = np.searchsorted(arr, 4)
print(z)

(array([3]),)
(array([1, 3, 5]),)
3


In [56]:
from re import M
arr = np.array([1,2,4,3,5,6],)
x = np.where(arr == 4)
print(x)

y = np.where(arr%2==0)
print(y)

z = np.searchsorted(arr, 7)
print(z)
m= np.sort(arr)
print(m)

(array([2]),)
(array([1, 2, 5]),)
6
[1 2 3 4 5 6]


In [57]:
x = np.random.randint(90,100)
print(x)

95


In [58]:
x = np.random.randint(10, size=(5))
print(x)

[3 8 8 5 6]
