# Array Initialization

In [3]:
import numpy as np

In [2]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [5]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
np.random.rand(4,2)

In [ ]:
np.random.randint(-4,8, size=(3,3))

In [ ]:
np.identity(5)

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

In [ ]:
a = np.array([[1,2,3,4],[2,3,5,6]])
b = np.array([[1,0,1,0],[6,7,8,9]])
c = np.concatenate((a,b), axis=1)
print(c)

In [ ]:
a = np.array([[1,2,3,4],[2,3,5,6]])
b = np.array([[1,0,1,0],[6,7,8,9]])
c = np.stack((a,b)) #stack
print(c)

In [ ]:
a = np.array([1,2,3,4,5,6,7,8])
array_split = np.split(a, 2)
print(array_split)
print(array_split[:1])

In [ ]:
arr = np.array([1,2,3,4,5,6])
x = np.where(arr == 4)
print(x)

y = np.where(arr%2==0)
print(y)

z = np.searchsorted(arr, 7)
print(z)

In [ ]:
from re import M
arr = np.array([1,2,4,3,5,6],)
x = np.where(arr == 4)
print(x)

y = np.where(arr%2==0)
print(y)

z = np.searchsorted(arr, 7)
print(z)
m= np.sort(arr)
print(m)

In [ ]:
x = np.random.randint(90,100)
print(x)

In [ ]:
x = np.random.randint(10, size=(5))
print(x)