# Array Initialization

In [2]:
import numpy as np

In [3]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [5]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [8]:
np.random.rand(4,2)

array([[9.85349016e-01, 1.10524208e-01],
       [4.12464318e-01, 1.55034889e-01],
       [8.24911492e-01, 3.04398047e-01],
       [6.60760325e-01, 9.38469013e-04]])

In [9]:
np.random.randint(-4,8, size=(3,3))

array([[ 4,  0,  6],
       [ 7,  1,  7],
       [-3, -1,  7]])

In [10]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [11]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [12]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]
