In [28]:
import numpy as np

In [29]:
arr = np.arange(10,51)  # make a array of element 
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [30]:
arr= np.random.randint(10,51,size =10)
print(arr)

arr= np.random.randint(10,512,size =(3,3,2,2,2))
print(arr)

[16 27 29 26 19 15 19 44 27 31]
[[[[[152  19]
    [305  42]]

   [[122 298]
    [387 215]]]


  [[[260 209]
    [255 249]]

   [[ 42  48]
    [167 183]]]


  [[[508 211]
    [404 122]]

   [[485 169]
    [444  37]]]]



 [[[[493  58]
    [ 95 323]]

   [[459 507]
    [122 494]]]


  [[[356 100]
    [391  18]]

   [[157 497]
    [260 206]]]


  [[[371 237]
    [ 59 225]]

   [[166 446]
    [295 398]]]]



 [[[[448 201]
    [453 357]]

   [[477 135]
    [251 184]]]


  [[[161  15]
    [ 59 224]]

   [[139 332]
    [481 180]]]


  [[[253 446]
    [255 342]]

   [[317  97]
    [116 446]]]]]


In [31]:
arr = np.random.randint(10,50,size = (1,10))
print(arr)

reshaped_array = arr.reshape(2,5)
print(reshaped_array)

[[26 30 37 37 17 39 22 32 48 16]]
[[26 30 37 37 17]
 [39 22 32 48 16]]


In [32]:
rand_arr = np.random.randint(1, 101, 20) 
mat_5x5 = np.arange(1, 26).reshape(5,5) 
mat_4x5 = rand_arr.reshape(4,5) 
print(mat_4x5,end="\n\n")
cols = mat_4x5[:, [1,3]]  # 2nd and 4th columns
print(cols)

[[ 2 68 65 91 74]
 [43 10 38 69 64]
 [91 27 67  5 44]
 [38 19 93 25 20]]

[[68 91]
 [10 69]
 [27  5]
 [19 25]]


In [ ]:
import numpy as np
arr = np.random.randint(10,500,size = (50))
print(arr)

for i in arr:
    if i%5 ==0:
        print(i)

[257 151  12 307 396 188 402 459 498 314  79 404 206 400 111  76 222 139
 194 149 257  36 265 378 473 287  10 158 424 297 296 285  40 341  15  55
 248 355 284  17 312  95 432 346 420 145 270 472 472 129]
400
265
10
285
40
15
55
355
95
420
145
270


In [6]:
import numpy as np
arr = np.random.randint(10,500,size = (1,2,50))
print(arr)

new_1D_arr = arr.flatten()
print(new_1D_arr)

[[[296 322  32 271 402  19 195 254 221 312 422  65 481 488 182  77 135
   386 467 382 104  58 198 156 155 300 427  80 370 334 482  46 297 416
    45 467  30  81 242 365 289 128 210 172 401  85  26 304  53  85]
  [224 491  44  57 119 420 218 431 473 356 368 103 347 393  13 419 254
   127 160 393  75  66 205 129  43 117 164 237 252 382 267 374 241 286
   313 370 267 126 463 463  81 454  12 200  93 329  20  42 106 219]]]
[296 322  32 271 402  19 195 254 221 312 422  65 481 488 182  77 135 386
 467 382 104  58 198 156 155 300 427  80 370 334 482  46 297 416  45 467
  30  81 242 365 289 128 210 172 401  85  26 304  53  85 224 491  44  57
 119 420 218 431 473 356 368 103 347 393  13 419 254 127 160 393  75  66
 205 129  43 117 164 237 252 382 267 374 241 286 313 370 267 126 463 463
  81 454  12 200  93 329  20  42 106 219]
